// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
lv_obj_t * ui_ScreenMain;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_LabelTime;
lv_obj_t * ui_LabelSecond;
lv_obj_t * ui_PanelAngle;
lv_obj_t * ui_ContainerPitch;
lv_obj_t * ui_LabelPitch;
lv_obj_t * ui_Label31;
lv_obj_t * ui_ContainerPitch1;
lv_obj_t * ui_LabelRoll;
lv_obj_t * ui_Label34;
lv_obj_t * ui_ContainerPitch2;
lv_obj_t * ui_LabelYaw;
lv_obj_t * ui_Label36;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_LabelVersion;
lv_obj_t * ui_PanelTempHumi;
lv_obj_t * ui_Panel5;
void ui_event_Image19(lv_event_t * e);
lv_obj_t * ui_Image19;
void ui_event_Image20(lv_event_t * e);
lv_obj_t * ui_Image20;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Label37;
lv_obj_t * ui_LabelTemp;
lv_obj_t * ui_LabelHumi;
lv_obj_t * ui_ImageWifi;
void ui_event_Image22(lv_event_t * e);
lv_obj_t * ui_Image22;
lv_obj_t * ui_Container3;
lv_obj_t * ui_LabelDate;
lv_obj_t * ui_LabelWeek;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenSet
void ui_ScreenSet_screen_init(void);
lv_obj_t * ui_ScreenSet;
lv_obj_t * ui_ContainerFunSet2;
lv_obj_t * ui_Label40;
lv_obj_t * ui_Container13;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Label41;
void ui_event_SliderVolume(lv_event_t * e);
lv_obj_t * ui_SliderVolume;
lv_obj_t * ui_PanelWifi1;
lv_obj_t * ui_Label42;
void ui_event_SwitchOnenet(lv_event_t * e);
lv_obj_t * ui_SwitchOnenet;
lv_obj_t * ui_PanelColor;
lv_obj_t * ui_Label43;
void ui_event_DropdownColor(lv_event_t * e);
lv_obj_t * ui_DropdownColor;
lv_obj_t * ui_PanelAlarm;
lv_obj_t * ui_Label3;
void ui_event_DropdownThreshold(lv_event_t * e);
lv_obj_t * ui_DropdownThreshold;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label15;
void ui_event_SliderThreshold(lv_event_t * e);
lv_obj_t * ui_SliderThreshold;
lv_obj_t * ui_LabelMinValue;
lv_obj_t * ui_LabelMaxValue;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Label1;
void ui_event_SliderVolume1(lv_event_t * e);
lv_obj_t * ui_SliderVolume1;
void ui_event_Image23(lv_event_t * e);
lv_obj_t * ui_Image23;
void ui_event_ButtonSave(lv_event_t * e);
lv_obj_t * ui_ButtonSave;
lv_obj_t * ui_Label2;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenMusic
void ui_ScreenMusic_screen_init(void);
lv_obj_t * ui_ScreenMusic;
lv_obj_t * ui_ContainerFunSet4;
lv_obj_t * ui_Image17;
lv_obj_t * ui_Label21;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenWeather
void ui_ScreenWeather_screen_init(void);
lv_obj_t * ui_ScreenWeather;
lv_obj_t * ui_Container7;
void ui_event_Image1(lv_event_t * e);
lv_obj_t * ui_Image1;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_LabelWeatherTemp;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_ImageWeather;
lv_obj_t * ui_LabelWeather;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_ImageCity;
lv_obj_t * ui_LabelWeatherCity;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_ImageHumi;
lv_obj_t * ui_LabelWeatherHumi;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_ImagePressure;
lv_obj_t * ui_LabelWeatherPressure;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_ImageWind;
lv_obj_t * ui_LabelWeatherWind;
lv_obj_t * ui_LabelWeatherdate;
void ui_event_ButtonWeatherUpdate(lv_event_t * e);
lv_obj_t * ui_ButtonWeatherUpdate;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Label24;
lv_obj_t * ui_labelUpdateStatus;
void ui_event_DropdownWeatherCity(lv_event_t * e);
lv_obj_t * ui_DropdownWeatherCity;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_1632112685[1] = {&ui_img_2084818829};
const lv_img_dsc_t * ui_imgset_1882733595[1] = {&ui_img_1466755499};
const lv_img_dsc_t * ui_imgset_95929285[1] = {&ui_img_1046395525};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Image19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_ScreenWeather, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenWeather_screen_init);
    }
}

void ui_event_Image20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSet, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenSet_screen_init);
    }
}

void ui_event_Image22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_ScreenMusic, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMusic_screen_init);
    }
}

void ui_event_SliderVolume(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        event_volume_Slider(e);
    }
}

void ui_event_SwitchOnenet(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        event_onenet_switch_clicked(e);
    }
}

void ui_event_DropdownColor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_background_dropdown(e);
    }
}

void ui_event_DropdownThreshold(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_threshold_dropdown(e);
    }
}

void ui_event_SliderThreshold(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        event_threshold_slider(e);
    }
}

void ui_event_SliderVolume1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        event_volume_Slider(e);
    }
}

void ui_event_Image23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
    }
}

void ui_event_ButtonSave(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        event_save_button(e);
    }
}

void ui_event_Image1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
    }
}

void ui_event_ButtonWeatherUpdate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        event_update_click(e);
    }
}

void ui_event_DropdownWeatherCity(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        event_WeatherCity_dropdown(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenMain_screen_init();
    ui_ScreenSet_screen_init();
    ui_ScreenMusic_screen_init();
    ui_ScreenWeather_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenMain);
}
