// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenMusic_screen_init(void)
{
    ui_ScreenMusic = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerFunSet4 = lv_obj_create(ui_ScreenMusic);
    lv_obj_remove_style_all(ui_ContainerFunSet4);
    lv_obj_set_width(ui_ContainerFunSet4, 240);
    lv_obj_set_height(ui_ContainerFunSet4, 295);
    lv_obj_set_x(ui_ContainerFunSet4, 0);
    lv_obj_set_y(ui_ContainerFunSet4, 5);
    lv_obj_set_align(ui_ContainerFunSet4, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerFunSet4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_img_create(ui_ContainerFunSet4);
    lv_img_set_src(ui_Image17, &ui_img_1609717271);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Image17, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Image17, lv_color_hex(0xB6EAF4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Image17, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label21 = lv_label_create(ui_ContainerFunSet4);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 0);
    lv_obj_set_y(ui_Label21, 3);
    lv_obj_set_align(ui_Label21, LV_ALIGN_TOP_MID);

    lv_obj_add_event_cb(ui_Image17, ui_event_Image17, LV_EVENT_ALL, NULL);

}
