// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenMain_screen_init(void)
{
    ui_ScreenMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenMain, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_Panel3, 135);
    lv_obj_set_height(ui_Panel3, 65);
    lv_obj_set_x(ui_Panel3, 2);
    lv_obj_set_y(ui_Panel3, 5);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x42A5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTime = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime, -10);
    lv_obj_set_y(ui_LabelTime, 0);
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "12:30");
    lv_obj_set_style_text_font(ui_LabelTime, &ui_font_siyuanMedium44_4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSecond = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_LabelSecond, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSecond, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSecond, 51);
    lv_obj_set_y(ui_LabelSecond, 21);
    lv_obj_set_align(ui_LabelSecond, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSecond, "30");

    ui_PanelAngle = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_PanelAngle, 224);
    lv_obj_set_height(ui_PanelAngle, 70);
    lv_obj_set_x(ui_PanelAngle, 6);
    lv_obj_set_y(ui_PanelAngle, 144);
    lv_obj_clear_flag(ui_PanelAngle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelAngle, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelAngle, lv_color_hex(0x42A5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelAngle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPitch = lv_obj_create(ui_PanelAngle);
    lv_obj_remove_style_all(ui_ContainerPitch);
    lv_obj_set_width(ui_ContainerPitch, 40);
    lv_obj_set_height(ui_ContainerPitch, 50);
    lv_obj_set_x(ui_ContainerPitch, -80);
    lv_obj_set_y(ui_ContainerPitch, -1);
    lv_obj_set_align(ui_ContainerPitch, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerPitch, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPitch = lv_label_create(ui_ContainerPitch);
    lv_obj_set_width(ui_LabelPitch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPitch, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPitch, 0);
    lv_obj_set_y(ui_LabelPitch, -5);
    lv_obj_set_align(ui_LabelPitch, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelPitch, "0");
    lv_obj_set_style_text_color(ui_LabelPitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPitch, &ui_font_siyuanMedium24_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_ContainerPitch);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label31, "Pitch");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0x212121), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPitch1 = lv_obj_create(ui_PanelAngle);
    lv_obj_remove_style_all(ui_ContainerPitch1);
    lv_obj_set_width(ui_ContainerPitch1, 40);
    lv_obj_set_height(ui_ContainerPitch1, 50);
    lv_obj_set_x(ui_ContainerPitch1, -7);
    lv_obj_set_y(ui_ContainerPitch1, 0);
    lv_obj_set_align(ui_ContainerPitch1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerPitch1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelRoll = lv_label_create(ui_ContainerPitch1);
    lv_obj_set_width(ui_LabelRoll, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRoll, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRoll, -1);
    lv_obj_set_y(ui_LabelRoll, -5);
    lv_obj_set_align(ui_LabelRoll, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelRoll, "0");
    lv_obj_set_style_text_color(ui_LabelRoll, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelRoll, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelRoll, &ui_font_siyuanMedium24_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_ContainerPitch1);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label34, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label34, "Roll");
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0x212121), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPitch2 = lv_obj_create(ui_PanelAngle);
    lv_obj_remove_style_all(ui_ContainerPitch2);
    lv_obj_set_width(ui_ContainerPitch2, 40);
    lv_obj_set_height(ui_ContainerPitch2, 50);
    lv_obj_set_x(ui_ContainerPitch2, 70);
    lv_obj_set_y(ui_ContainerPitch2, 0);
    lv_obj_set_align(ui_ContainerPitch2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerPitch2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelYaw = lv_label_create(ui_ContainerPitch2);
    lv_obj_set_width(ui_LabelYaw, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelYaw, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelYaw, -1);
    lv_obj_set_y(ui_LabelYaw, -5);
    lv_obj_set_align(ui_LabelYaw, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelYaw, "0");
    lv_obj_set_style_text_color(ui_LabelYaw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelYaw, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelYaw, &ui_font_siyuanMedium24_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_ContainerPitch2);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label36, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label36, "Yaw");
    lv_obj_set_style_text_color(ui_Label36, lv_color_hex(0x212121), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_PanelAngle);
    lv_obj_set_width(ui_Panel7, 1);
    lv_obj_set_height(ui_Panel7, 50);
    lv_obj_set_x(ui_Panel7, -46);
    lv_obj_set_y(ui_Panel7, 0);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x1976D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel7, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_PanelAngle);
    lv_obj_set_width(ui_Panel4, 1);
    lv_obj_set_height(ui_Panel4, 50);
    lv_obj_set_x(ui_Panel4, 32);
    lv_obj_set_y(ui_Panel4, 0);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x1976D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel4, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_Panel6, 240);
    lv_obj_set_height(ui_Panel6, 2);
    lv_obj_set_x(ui_Panel6, 0);
    lv_obj_set_y(ui_Panel6, -80);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelDate = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDate, -35);
    lv_obj_set_y(ui_LabelDate, 13);
    lv_obj_set_align(ui_LabelDate, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelDate, "10.30");

    ui_LabelWeek = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelWeek, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeek, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeek, -5);
    lv_obj_set_y(ui_LabelWeek, 38);
    lv_obj_set_align(ui_LabelWeek, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelWeek, "WEDNESDAY");

    ui_Label30 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, -78);
    lv_obj_set_y(ui_Label30, -76);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "version:0.1");

    ui_PanelTempHumi = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_PanelTempHumi, 143);
    lv_obj_set_height(ui_PanelTempHumi, 70);
    lv_obj_set_x(ui_PanelTempHumi, 39);
    lv_obj_set_y(ui_PanelTempHumi, -52);
    lv_obj_set_align(ui_PanelTempHumi, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTempHumi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTempHumi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTempHumi, lv_color_hex(0x1976D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTempHumi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_PanelTempHumi);
    lv_obj_set_width(ui_Panel5, 1);
    lv_obj_set_height(ui_Panel5, 50);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x42A5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel5, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image19 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image19, &ui_img_2084818829);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image19, 63);
    lv_obj_set_y(ui_Image19, -28);
    lv_obj_set_align(ui_Image19, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Image19, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Image19, lv_color_hex(0xDBF3F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Image19, lv_color_hex(0x42A5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Image19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Image19, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Image19, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Image19, lv_color_hex(0xB6EAF4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Image19, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image20 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image20, &ui_img_1046395525);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image20, 13);
    lv_obj_set_y(ui_Image20, -28);
    lv_obj_set_align(ui_Image20, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Image20, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Image20, lv_color_hex(0xDBF3F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Image20, lv_color_hex(0x42A5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Image20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Image20, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Image20, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Image20, lv_color_hex(0xB6EAF4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Image20, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label29 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -1);
    lv_obj_set_y(ui_Label29, -73);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "Temp");

    ui_Label37 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 67);
    lv_obj_set_y(ui_Label37, -73);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "Humi");

    ui_LabelTemp = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, 0);
    lv_obj_set_y(ui_LabelTemp, -46);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "25.5");
    lv_obj_set_style_text_color(ui_LabelTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemp, &ui_font_siyuanMedium24_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHumi = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelHumi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumi, 69);
    lv_obj_set_y(ui_LabelHumi, -46);
    lv_obj_set_align(ui_LabelHumi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumi, "70");
    lv_obj_set_style_text_color(ui_LabelHumi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHumi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHumi, &ui_font_siyuanMedium24_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWifi = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_ImageWifi, &ui_img_wifi_png);
    lv_obj_set_width(ui_ImageWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWifi, -80);
    lv_obj_set_y(ui_ImageWifi, -42);
    lv_obj_set_align(ui_ImageWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ImageWifi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImageWifi, lv_color_hex(0x75797A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImageWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image22 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image22, &ui_img_1413029994);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image22, 115);
    lv_obj_set_y(ui_Image22, -28);
    lv_obj_set_align(ui_Image22, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Image22, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Image22, lv_color_hex(0xDBF3F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Image22, lv_color_hex(0x42A5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Image22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Image22, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Image22, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Image22, lv_color_hex(0xB6EAF4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Image22, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_Image19, ui_event_Image19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image20, ui_event_Image20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image22, ui_event_Image22, LV_EVENT_ALL, NULL);

}
