// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenWeather_screen_init(void)
{
    ui_ScreenWeather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container7 = lv_obj_create(ui_ScreenWeather);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 240);
    lv_obj_set_height(ui_Container7, 295);
    lv_obj_set_x(ui_Container7, 0);
    lv_obj_set_y(ui_Container7, 5);
    lv_obj_set_align(ui_Container7, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Container7);
    lv_img_set_src(ui_Image1, &ui_img_1609717271);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Image1, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Image1, lv_color_hex(0xB6EAF4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Image1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label20 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 0);
    lv_obj_set_y(ui_Label20, 3);
    lv_obj_set_align(ui_Label20, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label20, "天气");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_siyuanMedium16_4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_ScreenWeather);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 100);
    lv_obj_set_height(ui_Container1, 20);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_Panel2, 120);
    lv_obj_set_height(ui_Panel2, 80);
    lv_obj_set_x(ui_Panel2, -39);
    lv_obj_set_y(ui_Panel2, -79);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xDBF3F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeatherTemp = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_LabelWeatherTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeatherTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeatherTemp, -13);
    lv_obj_set_y(ui_LabelWeatherTemp, -1);
    lv_obj_set_align(ui_LabelWeatherTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWeatherTemp, "26");
    lv_obj_set_style_text_font(ui_LabelWeatherTemp, &ui_font_siyuanMedium44_4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 32);
    lv_obj_set_y(ui_Label27, 11);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "℃");
    lv_obj_set_style_text_font(ui_Label27, &ui_font_siyuanMedium16_4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_Panel9, 60);
    lv_obj_set_height(ui_Panel9, 60);
    lv_obj_set_x(ui_Panel9, 65);
    lv_obj_set_y(ui_Panel9, -88);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWeather = lv_img_create(ui_Panel9);
    lv_img_set_src(ui_ImageWeather, &ui_img_rain_png);
    lv_obj_set_width(ui_ImageWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWeather, 0);
    lv_obj_set_y(ui_ImageWeather, -3);
    lv_obj_set_align(ui_ImageWeather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWeather, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelWeather = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeather, 67);
    lv_obj_set_y(ui_LabelWeather, -45);
    lv_obj_set_align(ui_LabelWeather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWeather, "Rain");

    ui_Panel10 = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_Panel10, 108);
    lv_obj_set_height(ui_Panel10, 30);
    lv_obj_set_x(ui_Panel10, -60);
    lv_obj_set_y(ui_Panel10, 29);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x8CC6F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageCity = lv_img_create(ui_Panel10);
    lv_img_set_src(ui_ImageCity, &ui_img_city_png);
    lv_obj_set_width(ui_ImageCity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageCity, -3);
    lv_obj_set_y(ui_ImageCity, 0);
    lv_obj_set_align(ui_ImageCity, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageCity, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelWeatherCity = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_LabelWeatherCity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeatherCity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWeatherCity, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelWeatherCity, "Enshi");

    ui_Panel1 = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_Panel1, 100);
    lv_obj_set_height(ui_Panel1, 30);
    lv_obj_set_x(ui_Panel1, 56);
    lv_obj_set_y(ui_Panel1, 29);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xEAF58C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageHumi = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_ImageHumi, &ui_img_humi_png);
    lv_obj_set_width(ui_ImageHumi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHumi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageHumi, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageHumi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHumi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelWeatherHumi = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelWeatherHumi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeatherHumi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWeatherHumi, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelWeatherHumi, "70%");

    ui_Panel11 = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_Panel11, 100);
    lv_obj_set_height(ui_Panel11, 30);
    lv_obj_set_x(ui_Panel11, 56);
    lv_obj_set_y(ui_Panel11, 66);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0xF099CC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImagePressure = lv_img_create(ui_Panel11);
    lv_img_set_src(ui_ImagePressure, &ui_img_airpressure_png);
    lv_obj_set_width(ui_ImagePressure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImagePressure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImagePressure, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImagePressure, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePressure, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelWeatherPressure = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_LabelWeatherPressure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeatherPressure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWeatherPressure, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelWeatherPressure, "1018");

    ui_Panel12 = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_Panel12, 108);
    lv_obj_set_height(ui_Panel12, 30);
    lv_obj_set_x(ui_Panel12, -60);
    lv_obj_set_y(ui_Panel12, 66);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xCDEC8C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWind = lv_img_create(ui_Panel12);
    lv_img_set_src(ui_ImageWind, &ui_img_wind_png);
    lv_obj_set_width(ui_ImageWind, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWind, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWind, -3);
    lv_obj_set_y(ui_ImageWind, 0);
    lv_obj_set_align(ui_ImageWind, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageWind, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWind, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelWeatherWind = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_LabelWeatherWind, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeatherWind, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeatherWind, -21);
    lv_obj_set_y(ui_LabelWeatherWind, 1);
    lv_obj_set_align(ui_LabelWeatherWind, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelWeatherWind, "4");

    ui_LabelWeatherdate = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelWeatherdate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeatherdate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeatherdate, 42);
    lv_obj_set_y(ui_LabelWeatherdate, -11);
    lv_obj_set_align(ui_LabelWeatherdate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWeatherdate, "2026-9-3");

    ui_ButtonWeatherUpdate = lv_btn_create(ui_ScreenWeather);
    lv_obj_set_width(ui_ButtonWeatherUpdate, 70);
    lv_obj_set_height(ui_ButtonWeatherUpdate, 30);
    lv_obj_set_x(ui_ButtonWeatherUpdate, 55);
    lv_obj_set_y(ui_ButtonWeatherUpdate, 118);
    lv_obj_set_align(ui_ButtonWeatherUpdate, LV_ALIGN_CENTER);

    ui_Label25 = lv_label_create(ui_ButtonWeatherUpdate);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 1);
    lv_obj_set_y(ui_Label25, 0);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "update");

    ui_Label24 = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -59);
    lv_obj_set_y(ui_Label24, -11);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "uptate time :");

    ui_labelUpdateStatus = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_labelUpdateStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelUpdateStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelUpdateStatus, 0);
    lv_obj_set_y(ui_labelUpdateStatus, -5);
    lv_obj_set_align(ui_labelUpdateStatus, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_labelUpdateStatus, "");

    ui_DropdownWeatherCity = lv_dropdown_create(ui_ScreenWeather);
    lv_dropdown_set_options(ui_DropdownWeatherCity, "Beijing\nShanghai\nEnshi\nZhuhai");
    lv_obj_set_width(ui_DropdownWeatherCity, 100);
    lv_obj_set_height(ui_DropdownWeatherCity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownWeatherCity, -60);
    lv_obj_set_y(ui_DropdownWeatherCity, 119);
    lv_obj_set_align(ui_DropdownWeatherCity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownWeatherCity, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    lv_obj_add_event_cb(ui_Image1, ui_event_Image1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonWeatherUpdate, ui_event_ButtonWeatherUpdate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DropdownWeatherCity, ui_event_DropdownWeatherCity, LV_EVENT_ALL, NULL);

}
