// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
extern lv_obj_t *ui_ScreenMain;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_LabelTime;
extern lv_obj_t *ui_LabelSecond;
extern lv_obj_t *ui_PanelAngle;
extern lv_obj_t *ui_ContainerPitch;
extern lv_obj_t *ui_LabelPitch;
extern lv_obj_t *ui_Label31;
extern lv_obj_t *ui_ContainerPitch1;
extern lv_obj_t *ui_LabelRoll;
extern lv_obj_t *ui_Label34;
extern lv_obj_t *ui_ContainerPitch2;
extern lv_obj_t *ui_LabelYaw;
extern lv_obj_t *ui_Label36;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_LabelVersion;
extern lv_obj_t *ui_PanelTempHumi;
extern lv_obj_t *ui_Panel5;
void ui_event_Image19(lv_event_t *e);
extern lv_obj_t *ui_Image19;
void ui_event_Image20(lv_event_t *e);
extern lv_obj_t *ui_Image20;
extern lv_obj_t *ui_Label29;
extern lv_obj_t *ui_Label37;
extern lv_obj_t *ui_LabelTemp;
extern lv_obj_t *ui_LabelHumi;
extern lv_obj_t *ui_ImageWifi;
void ui_event_Image22(lv_event_t *e);
extern lv_obj_t *ui_Image22;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_LabelDate;
extern lv_obj_t *ui_LabelWeek;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenSet
void ui_ScreenSet_screen_init(void);
extern lv_obj_t *ui_ScreenSet;
extern lv_obj_t *ui_ContainerFunSet2;
extern lv_obj_t *ui_Label40;
extern lv_obj_t *ui_Container13;
extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_Label41;
void ui_event_SliderVolume(lv_event_t *e);
extern lv_obj_t *ui_SliderVolume;
extern lv_obj_t *ui_PanelWifi1;
extern lv_obj_t *ui_Label42;
void ui_event_SwitchWifiSet(lv_event_t *e);
extern lv_obj_t *ui_SwitchWifiSet;
extern lv_obj_t *ui_PanelColor;
extern lv_obj_t *ui_Label43;
void ui_event_DropdownColor(lv_event_t *e);
extern lv_obj_t *ui_DropdownColor;
extern lv_obj_t *ui_PanelAlarm;
extern lv_obj_t *ui_Label3;
void ui_event_DropdownThreshold(lv_event_t *e);
extern lv_obj_t *ui_DropdownThreshold;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label15;
void ui_event_SliderThreshold(lv_event_t *e);
extern lv_obj_t *ui_SliderThreshold;
extern lv_obj_t *ui_LabelMinValue;
extern lv_obj_t *ui_LabelMaxValue;
extern lv_obj_t *ui_Panel13;
extern lv_obj_t *ui_Label1;
void ui_event_SliderVolume1(lv_event_t *e);
extern lv_obj_t *ui_SliderVolume1;
void ui_event_Image23(lv_event_t *e);
extern lv_obj_t *ui_Image23;
void ui_event_ButtonSave(lv_event_t *e);
extern lv_obj_t *ui_ButtonSave;
extern lv_obj_t *ui_Label2;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenMusic
void ui_ScreenMusic_screen_init(void);
extern lv_obj_t *ui_ScreenMusic;
extern lv_obj_t *ui_ContainerFunSet4;
extern lv_obj_t *ui_Image17;
extern lv_obj_t *ui_Label21;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenWeather
void ui_ScreenWeather_screen_init(void);
extern lv_obj_t *ui_ScreenWeather;
extern lv_obj_t *ui_Container7;
void ui_event_Image1(lv_event_t *e);
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Label20;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_LabelWeatherTemp;
extern lv_obj_t *ui_Label27;
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_ImageWeather;
extern lv_obj_t *ui_LabelWeather;
extern lv_obj_t *ui_Panel10;
extern lv_obj_t *ui_ImageCity;
extern lv_obj_t *ui_LabelWeatherCity;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_ImageHumi;
extern lv_obj_t *ui_LabelWeatherHumi;
extern lv_obj_t *ui_Panel11;
extern lv_obj_t *ui_ImagePressure;
extern lv_obj_t *ui_LabelWeatherPressure;
extern lv_obj_t *ui_Panel12;
extern lv_obj_t *ui_ImageWind;
extern lv_obj_t *ui_LabelWeatherWind;
extern lv_obj_t *ui_LabelWeatherdate;
void ui_event_ButtonWeatherUpdate(lv_event_t *e);
extern lv_obj_t *ui_ButtonWeatherUpdate;
extern lv_obj_t *ui_Label25;
extern lv_obj_t *ui_Label24;
extern lv_obj_t *ui_labelUpdateStatus;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_2084818829);      // assets/天气38_32.png
LV_IMG_DECLARE(ui_img_1046395525);      // assets/设置_32.png
LV_IMG_DECLARE(ui_img_wifi_png);        // assets/wifi.png
LV_IMG_DECLARE(ui_img_1413029994);      // assets/音乐.png
LV_IMG_DECLARE(ui_img_1609717271);      // assets/返回.png
LV_IMG_DECLARE(ui_img_rain_png);        // assets/Rain.png
LV_IMG_DECLARE(ui_img_snow_png);        // assets/snow.png
LV_IMG_DECLARE(ui_img_sunny_png);       // assets/sunny.png
LV_IMG_DECLARE(ui_img_cloudy_png);      // assets/cloudy.png
LV_IMG_DECLARE(ui_img_overcast_png);    // assets/overcast.png
LV_IMG_DECLARE(ui_img_city_png);        // assets/city.png
LV_IMG_DECLARE(ui_img_humi_png);        // assets/Humi.png
LV_IMG_DECLARE(ui_img_airpressure_png); // assets/AirPressure.png
LV_IMG_DECLARE(ui_img_wind_png);        // assets/Wind.png
LV_IMG_DECLARE(ui_img_1466755499);      // assets/环境监测_32.png

// FONTS
LV_FONT_DECLARE(ui_font_siyuanMedium20_2);
LV_FONT_DECLARE(ui_font_siyuanMedium44_4);
LV_FONT_DECLARE(ui_font_siyuanMedium16_4);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
