// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void event_update_click(lv_event_t * e)
{
	// Your code here
}

void event_volume_Slider(lv_event_t * e)
{
	// Your code here
}

void event_wifi_switch_clicked(lv_event_t * e)
{
	// Your code here
}

void event_background_dropdown(lv_event_t * e)
{
	// Your code here
}

void event_threshold_dropdown(lv_event_t * e)
{
	// Your code here
}

void event_threshold_slider(lv_event_t * e)
{
	// Your code here
}
