// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenSet_screen_init(void)
{
    ui_ScreenSet = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerFunSet2 = lv_obj_create(ui_ScreenSet);
    lv_obj_remove_style_all(ui_ContainerFunSet2);
    lv_obj_set_width(ui_ContainerFunSet2, 240);
    lv_obj_set_height(ui_ContainerFunSet2, 295);
    lv_obj_set_x(ui_ContainerFunSet2, 0);
    lv_obj_set_y(ui_ContainerFunSet2, 5);
    lv_obj_set_align(ui_ContainerFunSet2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerFunSet2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label40 = lv_label_create(ui_ContainerFunSet2);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, 0);
    lv_obj_set_y(ui_Label40, 3);
    lv_obj_set_align(ui_Label40, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label40, "设置");
    lv_obj_set_style_text_font(ui_Label40, &ui_font_siyuanMedium16_4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_ContainerFunSet2);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 220);
    lv_obj_set_height(ui_Container13, 264);
    lv_obj_set_x(ui_Container13, 0);
    lv_obj_set_y(ui_Container13, 32);
    lv_obj_set_align(ui_Container13, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container13, lv_color_hex(0x62BFCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Container13);
    lv_obj_set_width(ui_Panel8, 200);
    lv_obj_set_height(ui_Panel8, 38);
    lv_obj_set_x(ui_Panel8, 0);
    lv_obj_set_y(ui_Panel8, 84);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x43495E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label41, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label41, "音量");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &ui_font_siyuanMedium16_4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderVolume = lv_slider_create(ui_Panel8);
    lv_slider_set_value(ui_SliderVolume, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderVolume) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderVolume, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderVolume, 95);
    lv_obj_set_height(ui_SliderVolume, 4);
    lv_obj_set_align(ui_SliderVolume, LV_ALIGN_RIGHT_MID);


    ui_PanelWifi1 = lv_obj_create(ui_Container13);
    lv_obj_set_width(ui_PanelWifi1, 200);
    lv_obj_set_height(ui_PanelWifi1, 38);
    lv_obj_set_x(ui_PanelWifi1, 0);
    lv_obj_set_y(ui_PanelWifi1, 4);
    lv_obj_set_align(ui_PanelWifi1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelWifi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelWifi1, lv_color_hex(0x43495E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWifi1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_PanelWifi1);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label42, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label42, "Onenet");
    lv_obj_set_style_text_color(ui_Label42, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchOnenet = lv_switch_create(ui_PanelWifi1);
    lv_obj_set_width(ui_SwitchOnenet, 50);
    lv_obj_set_height(ui_SwitchOnenet, 25);
    lv_obj_set_align(ui_SwitchOnenet, LV_ALIGN_RIGHT_MID);


    ui_PanelColor = lv_obj_create(ui_Container13);
    lv_obj_set_width(ui_PanelColor, 200);
    lv_obj_set_height(ui_PanelColor, 38);
    lv_obj_set_x(ui_PanelColor, 0);
    lv_obj_set_y(ui_PanelColor, 44);
    lv_obj_set_align(ui_PanelColor, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelColor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelColor, lv_color_hex(0x43495E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelColor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_PanelColor);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label43, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label43, "背景颜色");
    lv_obj_set_style_text_color(ui_Label43, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label43, &ui_font_siyuanMedium16_4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownColor = lv_dropdown_create(ui_PanelColor);
    lv_dropdown_set_options(ui_DropdownColor, "white\npink\nblue\npurple");
    lv_obj_set_width(ui_DropdownColor, 80);
    lv_obj_set_height(ui_DropdownColor, 28);
    lv_obj_set_align(ui_DropdownColor, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_DropdownColor, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_PanelAlarm = lv_obj_create(ui_Container13);
    lv_obj_set_width(ui_PanelAlarm, 200);
    lv_obj_set_height(ui_PanelAlarm, 97);
    lv_obj_set_x(ui_PanelAlarm, 0);
    lv_obj_set_y(ui_PanelAlarm, 124);
    lv_obj_set_align(ui_PanelAlarm, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelAlarm, lv_color_hex(0x43495E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_PanelAlarm);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label3, "正常阈值");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_siyuanMedium16_4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownThreshold = lv_dropdown_create(ui_PanelAlarm);
    lv_dropdown_set_options(ui_DropdownThreshold, "Temp\nHumi\nPitch\nRoll\nYaw");
    lv_obj_set_width(ui_DropdownThreshold, 80);
    lv_obj_set_height(ui_DropdownThreshold, 30);
    lv_obj_set_x(ui_DropdownThreshold, 2);
    lv_obj_set_y(ui_DropdownThreshold, -28);
    lv_obj_set_align(ui_DropdownThreshold, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_DropdownThreshold, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Label5 = lv_label_create(ui_PanelAlarm);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label5, "Min:");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_PanelAlarm);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 84);
    lv_obj_set_y(ui_Label15, -1);
    lv_obj_set_align(ui_Label15, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label15, "Max:");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderThreshold = lv_slider_create(ui_PanelAlarm);
    lv_slider_set_mode(ui_SliderThreshold, LV_SLIDER_MODE_RANGE);
    lv_slider_set_value(ui_SliderThreshold, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderThreshold) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderThreshold, 25,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderThreshold, 160);
    lv_obj_set_height(ui_SliderThreshold, 4);
    lv_obj_set_x(ui_SliderThreshold, 0);
    lv_obj_set_y(ui_SliderThreshold, 5);
    lv_obj_set_align(ui_SliderThreshold, LV_ALIGN_CENTER);


    ui_LabelMinValue = lv_label_create(ui_PanelAlarm);
    lv_obj_set_width(ui_LabelMinValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMinValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMinValue, 35);
    lv_obj_set_y(ui_LabelMinValue, 0);
    lv_obj_set_align(ui_LabelMinValue, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LabelMinValue, "0");
    lv_obj_set_style_text_color(ui_LabelMinValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMinValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMaxValue = lv_label_create(ui_PanelAlarm);
    lv_obj_set_width(ui_LabelMaxValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMaxValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMaxValue, 120);
    lv_obj_set_y(ui_LabelMaxValue, 0);
    lv_obj_set_align(ui_LabelMaxValue, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LabelMaxValue, "2");
    lv_obj_set_style_text_color(ui_LabelMaxValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMaxValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_Container13);
    lv_obj_set_width(ui_Panel13, 200);
    lv_obj_set_height(ui_Panel13, 40);
    lv_obj_set_x(ui_Panel13, 0);
    lv_obj_set_y(ui_Panel13, 269);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x43495E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label1, "音量");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_siyuanMedium16_4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderVolume1 = lv_slider_create(ui_Panel13);
    lv_slider_set_value(ui_SliderVolume1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderVolume1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderVolume1, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderVolume1, 95);
    lv_obj_set_height(ui_SliderVolume1, 4);
    lv_obj_set_align(ui_SliderVolume1, LV_ALIGN_RIGHT_MID);


    ui_Image23 = lv_img_create(ui_ContainerFunSet2);
    lv_img_set_src(ui_Image23, &ui_img_1609717271);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Image23, 5, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Image23, lv_color_hex(0xB6EAF4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Image23, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ButtonSave = lv_btn_create(ui_ScreenSet);
    lv_obj_set_width(ui_ButtonSave, 40);
    lv_obj_set_height(ui_ButtonSave, 28);
    lv_obj_set_x(ui_ButtonSave, 64);
    lv_obj_set_y(ui_ButtonSave, 118);
    lv_obj_set_align(ui_ButtonSave, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonSave, lv_color_hex(0xEDE383), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_ButtonSave);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "保存");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x0C0B0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_siyuanMedium16_4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SliderVolume, ui_event_SliderVolume, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchOnenet, ui_event_SwitchOnenet, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DropdownColor, ui_event_DropdownColor, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DropdownThreshold, ui_event_DropdownThreshold, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderThreshold, ui_event_SliderThreshold, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderVolume1, ui_event_SliderVolume1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image23, ui_event_Image23, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSave, ui_event_ButtonSave, LV_EVENT_ALL, NULL);

}
