// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT Slider4

lv_obj_t * ui_Slider4_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Slider4;
    cui_Slider4 = lv_slider_create(comp_parent);
    lv_slider_set_value(cui_Slider4, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(cui_Slider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(cui_Slider4, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_Slider4, 150);
    lv_obj_set_height(cui_Slider4, 7);
    lv_obj_set_x(cui_Slider4, 5);
    lv_obj_set_y(cui_Slider4, -47);
    lv_obj_set_align(cui_Slider4, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SLIDER4_NUM);
    children[UI_COMP_SLIDER4_SLIDER4] = cui_Slider4;
    lv_obj_add_event_cb(cui_Slider4, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Slider4, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Slider4_create_hook(cui_Slider4);
    return cui_Slider4;
}

