// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_SLIDER4_H
#define _UI_COMP_SLIDER4_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Slider4
#define UI_COMP_SLIDER4_SLIDER4 0
#define _UI_COMP_SLIDER4_NUM 1
lv_obj_t * ui_Slider4_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
